// scripts/calibration/report.mjs
// Turn results/*.jsonl into lib/calibrationStats.json (committed, read by the
// public calibration page and the pricing page) and docs/CALIBRATION.md.
//
//   node scripts/calibration/report.mjs                     # newest run = primary
//   node scripts/calibration/report.mjs --primary gpt-5.1   # pick the primary model
//
// Refuses to mark the stats "published" unless the corpus manifest names a
// licence and the primary run cleared MIN_PUBLISHABLE_N essays. A page that
// quotes an accuracy figure must be able to say where the essays came from and
// under what licence; if it cannot, it says "calibration in progress" instead.
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { summarizeRun } from './metrics.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const RESULTS_DIR = join(HERE, 'results');
const MANIFEST_PATH = join(HERE, 'data', 'manifest.json');
const STATS_PATH = join(ROOT, 'lib', 'calibrationStats.json');
const DOC_PATH = join(ROOT, 'docs', 'CALIBRATION.md');

// Mirrors MIN_PUBLISHABLE_N in lib/calibrationStats.js. Kept as a literal here
// because this script runs under plain node and that module imports JSON.
const MIN_PUBLISHABLE_N = 100;

const CRITERIA = [
  { key: 'taskResponse', label: 'Task Response / Achievement' },
  { key: 'coherenceCohesion', label: 'Coherence & Cohesion' },
  { key: 'lexicalResource', label: 'Lexical Resource' },
  { key: 'grammaticalRange', label: 'Grammatical Range & Accuracy' },
];

function parseArgs(argv) {
  const args = {};
  for (let i = 0; i < argv.length; i += 1) {
    if (!argv[i].startsWith('--')) continue;
    const key = argv[i].slice(2);
    const next = argv[i + 1];
    if (next && !next.startsWith('--')) {
      args[key] = next;
      i += 1;
    } else args[key] = true;
  }
  return args;
}

function readJsonl(path) {
  return readFileSync(path, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .filter(Boolean);
}

function loadRuns() {
  if (!existsSync(RESULTS_DIR)) return [];
  return readdirSync(RESULTS_DIR)
    .filter((f) => f.endsWith('.jsonl'))
    .sort()
    .map((file) => {
      const rows = readJsonl(join(RESULTS_DIR, file));
      return {
        file,
        date: file.slice(0, 10),
        model: rows[0]?.model || file.slice(11).replace(/\.jsonl$/, ''),
        promptVersion: rows[0]?.promptVersion || null,
        rows,
      };
    })
    .filter((run) => run.rows.length);
}

function pct(value) {
  return value === null || value === undefined ? '—' : `${value}%`;
}

function num(value) {
  return value === null || value === undefined ? '—' : String(value);
}

function markdown({ stats, runs }) {
  const lines = [];
  lines.push('# AI Writing scorer calibration');
  lines.push('');
  lines.push('Generated by `node scripts/calibration/report.mjs`. Do not edit by hand.');
  lines.push('');
  if (stats.status !== 'published') {
    lines.push(`**Status: ${stats.status}.** ` + (stats.pendingReason || ''));
    lines.push('');
    lines.push('See `scripts/calibration/README.md` for what is blocking a published number.');
    lines.push('');
    return `${lines.join('\n')}`;
  }

  const p = stats.primary;
  lines.push(`- Corpus: ${stats.corpus.name} (${stats.corpus.licence})`);
  if (stats.corpus.url) lines.push(`- Source: ${stats.corpus.url}`);
  lines.push(`- Label scale: ${stats.corpus.scale}`);
  lines.push(`- Prompt version: \`${stats.promptVersion}\``);
  lines.push(`- Generated: ${stats.generatedAt}`);
  lines.push('');
  lines.push('## Headline');
  lines.push('');
  lines.push('| Model | n | MAE | Within 0.5 | Within 1.0 | Exact | Bias | Worst |');
  lines.push('| --- | --- | --- | --- | --- | --- | --- | --- |');
  [p, ...stats.comparison].forEach((run) => {
    lines.push(
      `| ${run.model} | ${run.n} | ${num(run.mae)} | ${pct(run.withinHalfPct)} | ${pct(
        run.withinOnePct
      )} | ${pct(run.exactPct)} | ${num(run.bias)} | ${num(run.maxError)} |`
    );
  });
  lines.push('');
  lines.push('## Error by human band');
  lines.push('');
  lines.push('| Human band | n | MAE | Bias | Within 0.5 |');
  lines.push('| --- | --- | --- | --- | --- |');
  p.byBand.forEach((b) => {
    lines.push(`| ${b.band.toFixed(1)} | ${b.n} | ${num(b.mae)} | ${num(b.bias)} | ${pct(b.withinHalfPct)} |`);
  });
  lines.push('');
  if (p.byCriterion.length) {
    lines.push('## Error by criterion');
    lines.push('');
    lines.push('| Criterion | n | MAE | Bias |');
    lines.push('| --- | --- | --- | --- |');
    p.byCriterion.forEach((c) => lines.push(`| ${c.label} | ${c.n} | ${num(c.mae)} | ${num(c.bias)} |`));
    lines.push('');
  }
  lines.push('## Confusion (human band x AI band)');
  lines.push('');
  lines.push(`| human \\ AI | ${p.confusion.aiBands.map((b) => b.toFixed(1)).join(' | ')} |`);
  lines.push(`| --- | ${p.confusion.aiBands.map(() => '---').join(' | ')} |`);
  p.confusion.humanBands.forEach((band, i) => {
    lines.push(`| **${band.toFixed(1)}** | ${p.confusion.matrix[i].join(' | ')} |`);
  });
  lines.push('');
  lines.push('## Runs included');
  lines.push('');
  runs.forEach((run) => lines.push(`- \`${run.file}\` — ${run.rows.length} rows, model ${run.model}`));
  lines.push('');
  return lines.join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  const runs = loadRuns();
  const manifest = existsSync(MANIFEST_PATH) ? JSON.parse(readFileSync(MANIFEST_PATH, 'utf8')) : null;
  const today = new Date().toISOString().slice(0, 10);

  let stats;
  if (!runs.length) {
    stats = {
      version: 1,
      status: 'pending',
      reviewedAt: today,
      generatedAt: null,
      promptVersion: null,
      corpus: null,
      primary: null,
      comparison: [],
      pendingReason: 'No scoring runs found in scripts/calibration/results/.',
    };
  } else {
    const primaryRun =
      (args.primary && runs.find((r) => r.model === args.primary)) || runs[runs.length - 1];
    const others = runs.filter((r) => r !== primaryRun);
    const primary = summarizeRun(primaryRun.rows, { model: primaryRun.model, criteria: CRITERIA });
    const comparison = others.map((run) => {
      const { byBand, confusion, byCriterion, ...headline } = summarizeRun(run.rows, {
        model: run.model,
        criteria: CRITERIA,
      });
      void byBand;
      void confusion;
      void byCriterion;
      return headline;
    });

    const licence = manifest?.corpus?.licence || null;
    const blockers = [];
    if (!licence) blockers.push('the corpus manifest does not name a licence');
    if (primary.n < MIN_PUBLISHABLE_N) {
      blockers.push(`only ${primary.n} essays were scored (minimum ${MIN_PUBLISHABLE_N})`);
    }

    stats = {
      version: 1,
      status: blockers.length ? 'pending' : 'published',
      reviewedAt: today,
      generatedAt: blockers.length ? null : primaryRun.date,
      promptVersion: primaryRun.promptVersion,
      corpus: manifest?.corpus || null,
      primary: blockers.length ? null : primary,
      comparison: blockers.length ? [] : comparison,
      ...(blockers.length ? { pendingReason: `Not published because ${blockers.join(' and ')}.` } : {}),
      // Kept even when pending so the operator can see what the run produced.
      ...(blockers.length ? { draft: { primary, comparison } } : {}),
    };
  }

  writeFileSync(STATS_PATH, `${JSON.stringify(stats, null, 2)}\n`, 'utf8');
  writeFileSync(DOC_PATH, markdown({ stats, runs }), 'utf8');

  console.log(`Status: ${stats.status}${stats.pendingReason ? ` — ${stats.pendingReason}` : ''}`);
  if (stats.primary) {
    console.log(
      `n=${stats.primary.n} MAE=${stats.primary.mae} within0.5=${stats.primary.withinHalfPct}% ` +
        `within1.0=${stats.primary.withinOnePct}% bias=${stats.primary.bias}`
    );
  }
  console.log(`Wrote ${STATS_PATH} and ${DOC_PATH}`);
}

main();
