// lib/calibrationStats.js
// The ONE reader for lib/calibrationStats.json — the measured accuracy of the
// AI Writing scorer. Both the public calibration page
// (pages/ielts-writing-checker-accuracy.js) and the pricing page read through
// here so a claim can never appear in one place and not the other, and so an
// empty/partial stats file renders nothing rather than "undefined%".
//
// The JSON is regenerated by `node scripts/calibration/report.mjs`. It ships in
// a "pending" state until a real run exists; every accessor below returns null
// in that state, which is what makes "render nothing when stats are empty"
// the default rather than something each caller has to remember.
import stats from './calibrationStats.json';

// A headline accuracy claim off a handful of essays is not a measurement, it is
// noise dressed up as one. Below this n the site says "calibration in progress"
// even if a results file exists.
export const MIN_PUBLISHABLE_N = 100;

export const CALIBRATION_STATS = stats;

function isNumber(value) {
  return typeof value === 'number' && Number.isFinite(value);
}

// True only when there is a real, large-enough, completed run to quote.
export function hasCalibrationStats() {
  const primary = stats?.primary;
  return Boolean(
    stats?.status === 'published' &&
      primary &&
      isNumber(primary.n) &&
      primary.n >= MIN_PUBLISHABLE_N &&
      isNumber(primary.withinHalfPct) &&
      isNumber(primary.mae)
  );
}

// The numbers the quick-answer capsule and the pricing line are built from.
// Returns null whenever a claim would not be honest.
export function calibrationHeadline() {
  if (!hasCalibrationStats()) return null;
  const { n, mae, bias, withinHalfPct, withinOnePct, exactPct, maxError, model } = stats.primary;
  return {
    n,
    mae,
    bias,
    withinHalfPct,
    withinOnePct,
    exactPct,
    maxError,
    model: model || null,
    corpusName: stats.corpus?.name || null,
    generatedAt: stats.generatedAt || null,
  };
}

// Percentages are stored to 1dp. Drop a trailing ".0" so the page reads
// "84%" rather than "84.0%", but keep a genuine half like "84.5%".
export function formatPct(value) {
  if (!isNumber(value)) return null;
  return `${Number.isInteger(value) ? value : value.toFixed(1)}%`;
}

// Bands are stored to 2dp. Always show two decimals for an error figure so
// "0.30" does not read as a rounder number than it is.
export function formatBandError(value) {
  if (!isNumber(value)) return null;
  return value.toFixed(2);
}

// Signed error, with the direction spelled out — a bare "-0.10" tells a reader
// nothing about which way the scorer leans.
export function formatBias(value) {
  if (!isNumber(value)) return null;
  if (Math.abs(value) < 0.005) return 'no measurable lean';
  const direction = value > 0 ? 'higher' : 'lower';
  return `${Math.abs(value).toFixed(2)} bands ${direction} than the human score, on average`;
}

// One sentence for the pricing page. Null when there is nothing truthful to say.
export function calibrationPricingLine() {
  const headline = calibrationHeadline();
  if (!headline) return null;
  return `Scorer accuracy: within 0.5 of the human band on ${formatPct(
    headline.withinHalfPct
  )} of ${headline.n.toLocaleString('en-GB')} human-scored essays`;
}

// "September 2026" for the visible "Updated" line. Falls back to the review
// date so the pending page still tells the reader how current it is.
export function calibrationUpdatedLabel() {
  const iso = stats?.generatedAt || stats?.reviewedAt;
  if (!iso) return null;
  const date = new Date(`${String(iso).slice(0, 10)}T00:00:00Z`);
  if (Number.isNaN(date.getTime())) return null;
  return date.toLocaleDateString('en-GB', { month: 'long', year: 'numeric', timeZone: 'UTC' });
}

// YYYY-MM-DD for schema.org dateModified.
export function calibrationDateModified() {
  const iso = stats?.generatedAt || stats?.reviewedAt;
  return iso ? String(iso).slice(0, 10) : null;
}
